
ies:
 properties:
   message: Welcome to IES- UAT Environment
   driver:
      class: oracle.jdbc.driver.OracleDriver
  
   url: jdbc:oracle:thin://localhost:1521:xe
   username: system
   password: admin
 
    
    
       